export {default as Home } from './Home'
export {default as About } from './About'
export {default as Contact } from './Contact'
export {default as Products } from './Product'
export {default as ProductShow} from './Product.show'
export {default as Dashboard } from './dashboard/Dashboard'
export {default as Login } from './Auth/Login'
export {default as Register } from './Auth/Register'
// export {default as Profile } from './Profile'
// export {default as Order } from './Order'
// export {default as NotFound } from './NotFound'